loadData;
% setCustomToolboxFiles;
% setOriginalToolboxFiles;
numberOfVariables = problemObj.lumCount * problemObj.nvars;

FitnessFunction = @(x) EAFitness(x, problemObj, lowRankObj, positionObj, luminarieObj);
CreationFcn = @(x, y, z) EAInit(x, y, z, variableMaxNeighborLumCount);
MutationFcn = @(t, u, v, w, x, y, z) EAMutation(t, u, v, w, x, y, z, problemObj, variableMaxNeighborLumCount);
CrossoverFunction = @(u, v, w, x, y, z) EACrossover(u, v, w, x, y, z);

% DOC: http://www.mathworks.com/help/gads/gaoptimset.html
options = gaoptimset(...
    'TolCon', 1e-3, ...
    'CreationFcn', CreationFcn, ...
    'CrossoverFcn', @crossovertwopoint, ...
    'CrossoverFraction', 0.8, ...
    'Display', 'diagnose', ... 'DistanceMeasureFcn', 1e-3, ... 'EliteCount', 2, ...
    'FitnessLimit', 0, ... 'FitnessScalingFcn', @algo, ... 'HybridFcn', [], ...
    'InitialPenalty', 0, ...
    'InitialPopulation', [], ... 'PopInitRange', 1e-3, ...
    'InitialScores', [], ...
    'Generations', 300, ...
    'StallGenLimit', 300, ...
    'StallTimeLimit', Inf, ...
    'TimeLimit', Inf, ...
    'MigrationDirection', 'forward', ...
    'MigrationFraction', 0.2, ...
    'MigrationInterval', 5, ...
    'MutationFcn', MutationFcn, ... 'NonlinConAlgorithm', 'penalty', ... 'OutputFcn', OutputFcn, ... 'ParetoFraction', 0.35, ...
    'PenaltyFactor', 100, ...
    'PlotFcn', [], ...
    'PlotInterval', 100, ...
    'PopulationSize', 10, ...
    'PopulationType', 'doubleVector', ...
    'SelectionFcn', @selectiontournament, ...
    'StallTest', 'averageChange', ...
    'UseParallel', false, ...
    'Vectorized', 'on' ...
);


% [x,fval,exitflag,output,population,scores] = ga(fitnessfcn,nvars,A,b,[],[],LB,UB,nonlcon,IntCon,options)
% DOC: http://www.mathworks.com/help/gads/ga.html
tic;
[x,fval,exitflag,output,population,scores] = wrapperGA(...
    FitnessFunction, ...
    numberOfVariables, ...
    [], ...
    [], ...
    [], ...
    [], ...
    [], ...
    [], ...
    [], ...
    options ...
);
toc