function [x,fval,exitflag,output,population,scores] = wrapperGA(FitnessFunction, numberOfVariables, ...
    unused1, ...
    unused2, ...
    unused3, ...
    unused4, ...
    unused5, ...
    unused6, ...
    unused7, ...
    options ...
)

[x,fval,exitflag,output,population,scores] = ga(...
    FitnessFunction, ...
    numberOfVariables, ...
    unused1, ...
    unused2, ...
    unused3, ...
    unused4, ...
    unused5, ...
    unused6, ...
    unused7, ...
    options ...
);
end

